version: "2.4"
#-------------------------------------------------------------------------------------
#- Ping Identity SPA Onboarding Guide
#-
#- To access PingAccess Console
#-
#-    https://localhost:9000/
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#
#- To access PingFederate Console
#-
#-    https://localhost:9999/pingfederate/app
#-
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingaccess:
    image: pingidentity/pingaccess:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/vikasgarghb/blog-ping-id
      - SERVER_PROFILE_PATH=server-profiles/pingaccess
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - "3000:3000"
      - "9000:9000"
    networks:
      - pingnet
    volumes:
      - pingaccess-out:/opt/out

  pingfederate:
    image: pingidentity/pingfederate:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/vikasgarghb/blog-ping-id
      - SERVER_PROFILE_PATH=server-profiles/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - pingfederate-out:/opt/out

networks:
  pingnet:

volumes:
  pingaccess-out:
  pingfederate-out:
