server:
  port: 8082
  ssl:
    key-store: ./certs/localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

trust-store:
  path: /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/conf/security/cacerts
  password: changeit

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://pingfederate:9031/ext/todoauthtoken/jwks
          issuer-uri: https://pingfederate:9031

auth:
  audience: vgarg.todo.pa.local:8082
