server:
  port: 8084
  ssl:
    key-store: ./certs/localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

auth:
  tokenEndpoint: https://pingfederate:9031/as/token.oauth2
  grantType: client_credentials

todo:
  serviceUrl: https://vgarg.todo.pa.local:3000
  audience: https://vgarg.todo.pa.local:3000
  clientId: todo_client
  clientSecret: toomanysecrets

tweet:
  serviceUrl: https://vgarg.tweet.pa.local:3000
  audience: https://vgarg.tweet.pa.local:3000
  clientId: tweet_client
  clientSecret: toomanysecrets
